# dbt_project.yml

# Nome do Projeto (devem conter apenas letras minúsculas e underscores)
name: 'dbt_northwind'
version: '1.0.0'

# Determina o `profile` a ser usado pelo dbt
profile: 'dbt_northwind'

# Configuração de pastas
model-paths: ["models"]
seed-paths: ["seeds"]
test-paths: ["data_tests"]
analysis-paths: ["analyses"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]
docs-paths: ["docs"]
asset-paths: ["assets"]

# Diretórios a serem removidos pelo comando `dbt clean`
clean-targets:
  - "target"
  - "dbt_packages"

# Configuração dos modelos: https://docs.getdbt.com/docs/configuring-models
models:
  dbt_northwind:

    # Camada de dados brutos (raw): snapshot dos dados da origem
    raw:
      +schema: raw
      +materialized: table
      +tags: ['raw', 'color:gray']

    # Camada staging (stg): transformações leves, renomeação e padronização
    stg:
      +schema: stg
      +materialized: view
      +tags: ['stg', 'color:blue']

    # Camada core: fatos e dimensões materializados como tabelas físicas
    core:
      +schema: core
      +materialized: table
      +tags: ['core', 'color:green']
    
    # Camada mart: dados agregados para dashboards e relatórios
    mart:
      +schema: mart
      +materialized: view
      +tags: ['mart', 'color:yellow']